version: '3.4'
services:
  pg:
    restart: always
    image: postgres 
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - PGDATA=/vm_pg/data
      - POSTGRES_PASSWORD=0c52788f-770c-4ddc-a6e3-19c324e1fb24
      - POSTGRES_USER=specification-studies
      - POSTGRES_DB=specification-studies-test
    volumes:
    - ./tmp/:/vm_pg/

